const entries=[
 {from:['Juicy Fruit','Mtume','1983'],to:['Juicy','The Notorious B.I.G.','1994'],note:'The sleek R&B groove becomes the foundation for Biggie’s story of making it.',source:'https://www.whosampled.com/news/2020/01/21/much-sampled-jazz-saxophonist-jimmy-heath-has-died-aged-93/'},
 {from:['The Way It Is','Bruce Hornsby and the Range','1986'],to:['Changes','2Pac','1998'],note:'That familiar piano line carries a new message about life, race and change.',source:'https://www.whosampled.com/2Pac/Changes/'},
 {from:['Walk on the Wild Side','Lou Reed','1972'],to:['Can I Kick It?','A Tribe Called Quest','1990'],note:'Listen for the bass line beneath Tribe’s easygoing call and response.',source:'https://www.whosampled.com/A-Tribe-Called-Quest/Can-I-Kick-It%3F/'},
 {from:["I Want’a Do Something Freaky to You",'Leon Haywood','1975'],to:["Nuthin’ but a ‘G’ Thang",'Dr. Dre feat. Snoop Dogg','1992'],note:'A slow soul groove becomes a defining West Coast sound.',source:'https://www.whosampled.com/Dr.-Dre/Nuthin%27-but-a-%27G%27-Thang/'},
 {from:["I Keep Forgettin’",'Michael McDonald','1982'],to:['Regulate','Warren G feat. Nate Dogg','1994'],note:'The smooth keyboard groove sets up a very different kind of nighttime story.',source:'https://www.whosampled.com/Warren-G/Regulate/'},
 {from:['Human Nature','Michael Jackson','1982'],to:["It Ain’t Hard to Tell",'Nas','1994'],note:'The soft pop atmosphere turns into a lyrical showcase.',source:'https://www.whosampled.com/Nas/It-Ain%27t-Hard-to-Tell/'},
 {from:["(Not Just) Knee Deep",'Funkadelic','1979'],to:['Me Myself and I','De La Soul','1989'],note:'Funkadelic’s bounce finds a playful new home in De La Soul’s breakout.',source:'https://www.whosampled.com/De-La-Soul/Me-Myself-and-I/'},
 {from:['Top Billin’','Audio Two','1987'],to:['Real Love','Mary J. Blige','1992'],note:'Hear the hard hip-hop drums that helped give this R&B classic its edge.',source:'https://www.whosampled.com/Mary-J.-Blige/Real-Love/'}
];
const yt=(artist,song)=>'https://www.youtube.com/results?search_query='+encodeURIComponent(artist+' '+song+' official audio');
const safe=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.getElementById('cards').innerHTML=entries.map((e,i)=>`<article class="card" data-number="${String(i+1).padStart(2,'0')}"><div class="card-head"><span class="index">ROOT ${String(i+1).padStart(2,'0')}</span><span>${safe(e.from[2])} / ${safe(e.to[2])}</span></div><div class="pair"><div><div class="label">THE ORIGINAL</div><h3 class="song">${safe(e.from[0])}</h3><div class="artist">${safe(e.from[1])}</div></div><span class="arrow" aria-hidden="true">→</span><div><div class="label">THE FLIP</div><h3 class="song">${safe(e.to[0])}</h3><div class="artist">${safe(e.to[1])}</div></div></div><p class="note">${safe(e.note)}</p><div class="actions"><a class="listen" target="_blank" rel="noopener noreferrer" href="${yt(e.from[1],e.from[0])}" aria-label="Find ${safe(e.from[0])} by ${safe(e.from[1])} on YouTube">FIND ORIGINAL ↗</a><a class="listen" target="_blank" rel="noopener noreferrer" href="${yt(e.to[1],e.to[0])}" aria-label="Find ${safe(e.to[0])} by ${safe(e.to[1])} on YouTube">FIND FLIP ↗</a></div><div class="source">Sample relationship: <a target="_blank" rel="noopener noreferrer" href="${e.source}">source ↗</a></div></article>`).join('');
